### ISSUE TITLE
Hover Canvas/HTML Target

### ISSUE THREAD

**Issue by TommasoBelluzzo** [timdream/wordcloud2.js#68] opened 2016-02-27 04:54 UTC
I'm having a problem with hover event in my word clouds. Actually I don't know if it depends on the position of the parent elements or something like this, but the event is almost never returning the correct word I'm hovering on both canvas and HTML. On a canvas contained in a right floating div the event is not even firing.

**Comment by timdream** [comment] 2016-02-27 05:19
There was a regression caused by 625d6f90 and fixed by 0638574. Did you update to that commit?

**Comment by timdream** [comment] 2016-02-27 05:21
... and I published a new version on npm: v1.0.3 too.

**Comment by timdream** [comment] 2016-02-27 05:24
Issue #66 was fixed so this is likely fixed too. Please comment if it didn't. Thanks!

**Closed as completed by timdream** 2016-02-27 05:24 UTC
